- name: Inject Secrets
        run: |
          sed -i "s|PROD_URL_PLACEHOLDER|${{ secrets.SUPABASE_URL }}|g" index.html
          sed -i "s|PROD_KEY_PLACEHOLDER|${{ secrets.SUPABASE_KEY }}|g" index.html
          sed -i "s|VITALIS_URL_PLACEHOLDER|${{ secrets.VITALIS_URL }}|g" index.html
          sed -i "s|VITALIS_KEY_PLACEHOLDER|${{ secrets.VITALIS_KEY }}|g" index.html
